In [1]:
import pandas as pd

In [15]:
df = pd.read_csv("balance.txt", sep=" ")
print(df)

       Balance   Income  Limit  Rating  Cards  Age  Education  Gender Student  \
0    12.240798   14.891   3606     283      2   34         11    Male      No
1    23.283334  106.025   6645     483      3   82         15  Female     Yes
2    22.530409  104.593   7075     514      4   71         11    Male      No
3    27.652811  148.924   9504     681      3   36         11  Female      No
4    16.893978   55.882   4897     357      2   68         16    Male      No
..         ...      ...    ...     ...    ...  ...        ...     ...     ...
395   8.764984   12.096   4100     307      3   32         13    Male      No
396   9.943838   13.364   3838     296      5   65         17    Male      No
397  14.882078   57.872   4171     321      5   67         12  Female      No
398  12.001071   37.728   2525     192      1   44         13    Male      No
399  10.159598   18.701   5524     415      5   64          7  Female      No

    Married         Ethnicity
0       Yes         Caucasian
1       Yes             Asian
2        No             Asian
3        No             Asian
4       Yes         Caucasian
..      ...               ...
395     Yes         Caucasian
396      No  African American
397     Yes         Caucasian
398     Yes         Caucasian
399      No             Asian

[400 rows x 11 columns]

Write the code needed to produce a report that provides the following information:
* Compare the average income based on ethnicity. 
* On average, do married or single people have a higher balance?
* What is the highest income in our dataset?
* What is the lowest income in our dataset?
* How many cards do we have recorded in our dataset? (Hint: use `sum()`)
* How many females do we have information for vs how many males? (Hint: use `count()`For a list of all methods for computation of descriptive stats, explore the [pandas documentation](https://pandas.pydata.org/pandas-docs/stable/reference/frame.html#computations-descriptive-stats)).

In [11]:
ethnicity_ave_income = df.groupby('Ethnicity')['Income'].mean()
print(ethnicity_ave_income)

Ethnicity
African American    47.682098
Asian               44.187836
Caucasian           44.671593
Name: Income, dtype: float32

In [10]:
married_balance = df.loc[df["Married"] == "Yes", "Balance"].mean()
single_balance = df.loc[df["Married"] == "No", "Balance"].mean()

print("Married mean balance: ", married_balance)
print("Single mean balance: ", single_balance)

if married_balance > single_balance:
    print("Married has a higher balance.")
else:
    print("Single has a higher balance.")

Married mean balance:  13.393177
Single mean balance:  13.493509
Single individuals have a higher balance.

In [6]:
max_income = df['Income'].max()
print(max_income)

The maximum income is: 186.634

In [7]:
min_income = df['Income'].min()
print(min_income)

The minimum income is: 10.354

In [24]:
count = 0

for i in df['Cards']:
    print (i)
    count += i 
    print (count)

2
2
3
5
4
9
3
12
2
14
4
18
2
20
2
22
5
27
3
30
4
34
3
37
1
38
1
39
2
41
3
44
3
47
3
50
1
51
2
53
4
57
1
58
3
61
5
66
3
69
5
74
6
80
2
82
2
84
4
88
4
92
5
97
2
99
4
103
2
105
3
108
2
110
2
112
4
116
4
120
3
123
2
125
2
127
1
128
3
131
3
134
2
136
2
138
6
144
4
148
3
151
2
153
1
154
4
158
2
160
2
162
7
169
4
173
2
175
4
179
2
181
3
184
2
186
4
190
2
192
4
196
4
200
4
204
2
206
4
210
4
214
2
216
1
217
4
221
4
225
2
227
1
228
1
229
3
232
2
234
3
237
1
238
3
241
3
244
4
248
4
252
1
253
4
257
4
261
3
264
4
268
3
271
4
275
2
277
3
280
5
285
1
286
4
290
2
292
5
297
1
298
3
301
2
303
6
309
4
313
2
315
2
317
3
320
4
324
5
329
3
332
2
334
4
338
4
342
4
346
5
351
3
354
1
355
3
358
3
361
2
363
2
365
1
366
3
369
1
370
1
371
5
376
3
379
2
381
3
384
4
388
5
393
4
397
4
401
3
404
3
407
2
409
4
413
2
415
3
418
3
421
2
423
3
426
3
429
3
432
2
434
3
437
3
440
2
442
5
447
3
450
3
453
4
457
3
460
2
462
4
466
5
471
2
473
2
475
3
478
5
483
3
486
1
487
5
492
4
496
4
500
2
502
1
503
1
504
4
508
3
511
1
512
4
516
3
519
3
522
3
525
4
529
2
531
2
533
5
538
5
543
3
546
2
548
3
551
1
552
1
553
2
555
2
557
2
559
2
561
4
565
3
568
4
572
7
579
2
581
2
583
1
584
2
586
4
590
3
593
2
595
6
601
2
603
5
608
2
610
8
618
2
620
5
625
3
628
2
630
2
632
3
635
2
637
2
639
2
641
3
644
3
647
3
650
2
652
4
656
3
659
5
664
4
668
5
673
4
677
4
681
6
687
3
690
2
692
3
695
3
698
4
702
1
703
3
706
3
709
3
712
2
714
5
719
6
725
1
726
5
731
2
733
3
736
1
737
4
741
5
746
4
750
3
753
1
754
3
757
2
759
5
764
3
767
6
773
4
777
3
780
2
782
1
783
2
785
6
791
4
795
3
798
1
799
2
801
1
802
3
805
4
809
3
812
4
816
4
820
1
821
1
822
2
824
6
830
5
835
3
838
2
840
2
842
2
844
3
847
3
850
3
853
2
855
3
858
2
860
2
862
2
864
4
868
3
871
2
873
5
878
4
882
2
884
7
891
4
895
5
900
1
901
3
904
1
905
3
908
1
909
3
912
1
913
1
914
2
916
2
918
3
921
3
924
2
926
3
929
1
930
3
933
6
939
2
941
2
943
3
946
2
948
2
950
3
953
5
958
3
961
2
963
6
969
4
973
2
975
1
976
3
979
3
982
3
985
2
987
2
989
2
991
3
994
2
996
2
998
2
1000
4
1004
3
1007
1
1008
1
1009
4
1013
2
1015
5
1020
2
1022
7
1029
2
1031
5
1036
2
1038
3
1041
3
1044
4
1048
1
1049
2
1051
2
1053
1
1054
2
1056
3
1059
1
1060
1
1061
3
1064
4
1068
2
1070
3
1073
1
1074
3
1077
4
1081
3
1084
2
1086
3
1089
3
1092
4
1096
4
1100
2
1102
2
1104
3
1107
5
1112
2
1114
3
1117
1
1118
1
1119
3
1122
2
1124
1
1125
9
1134
3
1137
3
1140
4
1144
3
1147
2
1149
2
1151
3
1154
2
1156
2
1158
2
1160
4
1164
3
1167
5
1172
5
1177
1
1178
5
1183

In [25]:
female_count = len(df[df["Gender"] == "Female"])
male_count = len(df[df["Gender"] == "Male"])

print("Number of females:", female_count)
print("Number of males:", male_count)

Number of females: 207
Number of males: 193